swagger: "2.0"
/uploads:
 post:
    tags:
      - uploads
    summary: uploads an image (GC Storage)
    x-swagger-router-controller: SampleController
    description: ""
    operationId: uploadFile
    consumes:
      - multipart/form-data
    produces:
      - application/json
    parameters:
      - name: file
        in: formData
        description: file to upload
        required: false
        type: file
    responses:
      "200":
        description: successful operation
        schema:
          $ref: "#/definitions/ApiResponse"
    security:
      - petstore_auth:
          - "write:pets"
          - "read:pets"
/uploads/file:
  post:
      tags:
        - uploads
      summary: uploads an image (S3)
      x-swagger-router-controller: SampleController
      description: ""
      operationId: uploadS3File
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          in: formData
          description: file to upload
          required: false
          type: file
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
